wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.20
    cli_version: 0.16.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730852682.613269
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.20
      5: 0.16.0
      8:
      - 5
      13: darwin-x86_64
mlflow_model:
  desc: null
  value: random_forest_export:prod
test_dataset:
  desc: null
  value: test_data.csv:latest
